# Generated by Django 4.2.14 on 2024-08-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_certification_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='slug',
        ),
    ]
