# Generated by Django 4.2.14 on 2024-08-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certification_image',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
