# Generated by Django 4.2.14 on 2024-08-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
